#**************************************************************************
#*************             BittWare Incorporated              *************
#*************      45 S. Main Street, Concord, NH 03301      *************
#**************************************************************************
# LEGAL NOTICE:
#                 Copyright (c) 2016 BittWare, Inc.
#   The user is hereby granted a non-exclusive license to use and or
#     modify this code provided that it runs on BittWare hardware.
#   Usage of this code on non-BittWare hardware without the express
#      written permission of BittWare is strictly prohibited.
#
# E-mail: support@bittware.com                    Tel: 603-226-0404
#**************************************************************************

### Created by: Jeff Sanders
### Date: 29 Aug 2017
###
### Constraints for the integrated example project for the BittWare XUSPL4. ###
###

##############################################
##########      Memory Clocks       ##########
##############################################
# NOTE: Currently using 100 MHz system clock, subject to change
create_clock -period 10.00 [get_ports ddr4_bank0_clk_clk_p]
create_clock -period 10.00 [get_ports ddr4_bank1_clk_clk_p]

set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports ddr4_bank0_clk_clk_p]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports ddr4_bank0_clk_clk_n]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports ddr4_bank1_clk_clk_p]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports ddr4_bank1_clk_clk_n]
set_property ODT RTT_48                 [get_ports ddr4_bank0_clk_clk_p]
set_property ODT RTT_48                 [get_ports ddr4_bank1_clk_clk_p]
set_property PACKAGE_PIN J11            [get_ports ddr4_bank0_clk_clk_p]
set_property PACKAGE_PIN AM14           [get_ports ddr4_bank1_clk_clk_p]

set_clock_groups -group [get_clocks ddr4_bank0_clk_clk_p -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks ddr4_bank1_clk_clk_p -include_generated_clocks] -asynchronous

##############################################
##########   DDR4 Pin Properties    ##########
##############################################

#
# Bank A
#
set_property PACKAGE_PIN G12 [get_ports {m0_ddr4_odt[0]}]
set_property PACKAGE_PIN J8  [get_ports m0_ddr4_reset_n]
set_property PACKAGE_PIN K12 [get_ports m0_ddr4_act_n]
set_property PACKAGE_PIN J9  [get_ports {m0_ddr4_cke[0]}]
set_property PACKAGE_PIN H8  [get_ports {m0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN K15 [get_ports {m0_ddr4_dq[19]}]
set_property PACKAGE_PIN A18 [get_ports {m0_ddr4_dq[60]}]
set_property PACKAGE_PIN A19 [get_ports {m0_ddr4_dq[61]}]
set_property PACKAGE_PIN A22 [get_ports {m0_ddr4_dq[62]}]
set_property PACKAGE_PIN B19 [get_ports {m0_ddr4_dq[56]}]
set_property PACKAGE_PIN B20 [get_ports {m0_ddr4_dm_n[7]}]
set_property PACKAGE_PIN C21 [get_ports {m0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN B21 [get_ports {m0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN E20 [get_ports {m0_ddr4_dm_n[6]}]
set_property PACKAGE_PIN E21 [get_ports {m0_ddr4_dq[55]}]
set_property PACKAGE_PIN F22 [get_ports {m0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN E22 [get_ports {m0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN N22 [get_ports {m0_ddr4_dm_n[4]}]
set_property PACKAGE_PIN M21 [get_ports {m0_ddr4_dq[32]}]
set_property PACKAGE_PIN M20 [get_ports {m0_ddr4_dq[37]}]
set_property PACKAGE_PIN M19 [get_ports {m0_ddr4_dq[34]}]
set_property PACKAGE_PIN L22 [get_ports {m0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN K22 [get_ports {m0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN L20 [get_ports {m0_ddr4_dq[36]}]
set_property PACKAGE_PIN L19 [get_ports {m0_ddr4_dq[39]}]
set_property PACKAGE_PIN L18 [get_ports {m0_ddr4_dq[38]}]
set_property PACKAGE_PIN K21 [get_ports {m0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN K20 [get_ports {m0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN K18 [get_ports {m0_ddr4_dq[43]}]
set_property PACKAGE_PIN J20 [get_ports {m0_ddr4_dq[45]}]
set_property PACKAGE_PIN J18 [get_ports {m0_ddr4_dq[42]}]
set_property PACKAGE_PIN H19 [get_ports {m0_ddr4_dq[41]}]
set_property PACKAGE_PIN H18 [get_ports {m0_ddr4_dq[40]}]
set_property PACKAGE_PIN G22 [get_ports {m0_ddr4_dq[47]}]
set_property PACKAGE_PIN G21 [get_ports {m0_ddr4_dq[46]}]
set_property PACKAGE_PIN G20 [get_ports {m0_ddr4_dq[51]}]
set_property PACKAGE_PIN G19 [get_ports {m0_ddr4_dq[50]}]
set_property PACKAGE_PIN F20 [get_ports {m0_ddr4_dq[49]}]
set_property PACKAGE_PIN F19 [get_ports {m0_ddr4_dq[48]}]
set_property PACKAGE_PIN F18 [get_ports {m0_ddr4_dq[53]}]
set_property PACKAGE_PIN E18 [get_ports {m0_ddr4_dq[52]}]
set_property PACKAGE_PIN D21 [get_ports {m0_ddr4_dq[54]}]
set_property PACKAGE_PIN D18 [get_ports {m0_ddr4_dq[59]}]
set_property PACKAGE_PIN C19 [get_ports {m0_ddr4_dq[57]}]
set_property PACKAGE_PIN C18 [get_ports {m0_ddr4_dq[58]}]
set_property PACKAGE_PIN B22 [get_ports {m0_ddr4_dq[63]}]
set_property PACKAGE_PIN H22 [get_ports {m0_ddr4_dm_n[5]}]
set_property PACKAGE_PIN D10 [get_ports {m0_ddr4_adr[6]}]
set_property PACKAGE_PIN D11 [get_ports {m0_ddr4_adr[3]}]
set_property PACKAGE_PIN E8  [get_ports {m0_ddr4_adr[1]}]
set_property PACKAGE_PIN E10 [get_ports {m0_ddr4_ba[1]}]
set_property PACKAGE_PIN E11 [get_ports {m0_ddr4_adr[2]}]
set_property PACKAGE_PIN E12 [get_ports {m0_ddr4_adr[5]}]
set_property PACKAGE_PIN F8  [get_ports {m0_ddr4_adr[0]}]
set_property PACKAGE_PIN F9  [get_ports {m0_ddr4_bg[1]}]
set_property PACKAGE_PIN F10 [get_ports {m0_ddr4_ba[0]}]
set_property PACKAGE_PIN F12 [get_ports {m0_ddr4_adr[4]}]
set_property PACKAGE_PIN A9  [get_ports {m0_ddr4_adr[10]}]
set_property PACKAGE_PIN M22 [get_ports {m0_ddr4_dq[33]}]
set_property PACKAGE_PIN N19 [get_ports {m0_ddr4_dq[35]}]
set_property PACKAGE_PIN A12 [get_ports {m0_ddr4_adr[16]}]
set_property PACKAGE_PIN A13 [get_ports {m0_ddr4_adr[15]}]
set_property PACKAGE_PIN B9  [get_ports {m0_ddr4_adr[9]}]
set_property PACKAGE_PIN B11 [get_ports {m0_ddr4_adr[12]}]
set_property PACKAGE_PIN B12 [get_ports {m0_ddr4_adr[14]}]
set_property PACKAGE_PIN C9  [get_ports {m0_ddr4_adr[8]}]
set_property PACKAGE_PIN C11 [get_ports {m0_ddr4_adr[11]}]
set_property PACKAGE_PIN C12 [get_ports {m0_ddr4_adr[13]}]
set_property PACKAGE_PIN D9  [get_ports {m0_ddr4_adr[7]}]
set_property PACKAGE_PIN L14 [get_ports {m0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN L17 [get_ports {m0_ddr4_dq[24]}]
set_property PACKAGE_PIN M14 [get_ports {m0_ddr4_dq[26]}]
set_property PACKAGE_PIN M15 [get_ports {m0_ddr4_dq[27]}]
set_property PACKAGE_PIN M16 [get_ports {m0_ddr4_dq[28]}]
set_property PACKAGE_PIN M17 [get_ports {m0_ddr4_dq[25]}]
set_property PACKAGE_PIN N16 [get_ports {m0_ddr4_dq[29]}]
set_property PACKAGE_PIN N17 [get_ports {m0_ddr4_dq[30]}]
set_property PACKAGE_PIN N18 [get_ports {m0_ddr4_dq[31]}]
set_property PACKAGE_PIN P14 [get_ports {m0_ddr4_dm_n[3]}]
set_property PACKAGE_PIN H14 [get_ports {m0_ddr4_dq[20]}]
set_property PACKAGE_PIN H16 [get_ports {m0_ddr4_dq[16]}]
set_property PACKAGE_PIN J13 [get_ports {m0_ddr4_dm_n[2]}]
set_property PACKAGE_PIN J14 [get_ports {m0_ddr4_dq[21]}]
set_property PACKAGE_PIN J15 [get_ports {m0_ddr4_dq[18]}]
set_property PACKAGE_PIN J16 [get_ports {m0_ddr4_dq[17]}]
set_property PACKAGE_PIN K13 [get_ports {m0_ddr4_dq[22]}]
set_property PACKAGE_PIN K16 [get_ports {m0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN E13 [get_ports {m0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN E15 [get_ports {m0_ddr4_dq[10]}]
set_property PACKAGE_PIN E16 [get_ports {m0_ddr4_dq[11]}]
set_property PACKAGE_PIN E17 [get_ports {m0_ddr4_dq[8]}]
set_property PACKAGE_PIN F14 [get_ports {m0_ddr4_dq[14]}]
set_property PACKAGE_PIN F15 [get_ports {m0_ddr4_dq[15]}]
set_property PACKAGE_PIN F17 [get_ports {m0_ddr4_dq[9]}]
set_property PACKAGE_PIN G15 [get_ports {m0_ddr4_dm_n[1]}]
set_property PACKAGE_PIN G16 [get_ports {m0_ddr4_dq[12]}]
set_property PACKAGE_PIN G17 [get_ports {m0_ddr4_dq[13]}]
set_property PACKAGE_PIN A14 [get_ports {m0_ddr4_dq[2]}]
set_property PACKAGE_PIN A15 [get_ports {m0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN A17 [get_ports {m0_ddr4_dq[0]}]
set_property PACKAGE_PIN B14 [get_ports {m0_ddr4_dq[3]}]
set_property PACKAGE_PIN B16 [get_ports {m0_ddr4_dq[4]}]
set_property PACKAGE_PIN B17 [get_ports {m0_ddr4_dq[1]}]
set_property PACKAGE_PIN C16 [get_ports {m0_ddr4_dq[5]}]
set_property PACKAGE_PIN D14 [get_ports {m0_ddr4_dm_n[0]}]
set_property PACKAGE_PIN D15 [get_ports {m0_ddr4_dq[6]}]
set_property PACKAGE_PIN D16 [get_ports {m0_ddr4_dq[7]}]
set_property PACKAGE_PIN L13 [get_ports {m0_ddr4_dq[23]}]
set_property PACKAGE_PIN G9  [get_ports {m0_ddr4_bg[0]}]
set_property PACKAGE_PIN J19 [get_ports {m0_ddr4_dq[44]}]
set_property PACKAGE_PIN F7  [get_ports {m0_ddr4_ck_c[0]}]

#
# Bank A - ECC pins
#
#set_property PACKAGE_PIN K10 [get_ports {m0_ddr4_dq[64]}]
#set_property PACKAGE_PIN K11 [get_ports {m0_ddr4_dq[65]}]
#set_property PACKAGE_PIN L9  [get_ports {m0_ddr4_dq[66]}]
#set_property PACKAGE_PIN L10 [get_ports {m0_ddr4_dq[67]}]
#set_property PACKAGE_PIN M10 [get_ports {m0_ddr4_dq[68]}]
#set_property PACKAGE_PIN M11 [get_ports {m0_ddr4_dq[69]}]
#set_property PACKAGE_PIN M9  [get_ports {m0_ddr4_dq[70]}]
#set_property PACKAGE_PIN N9  [get_ports {m0_ddr4_dq[71]}]
#set_property PACKAGE_PIN N12 [get_ports {m0_ddr4_dm_n[8]}]
#set_property PACKAGE_PIN L12 [get_ports {m0_ddr4_dqs_c[8]}]


#
# Bank B
#
set_property PACKAGE_PIN AK13 [get_ports m1_ddr4_act_n]
set_property PACKAGE_PIN AM13 [get_ports {m1_ddr4_cke[0]}]
set_property PACKAGE_PIN AM17 [get_ports {m1_ddr4_cs_n[0]}]
set_property PACKAGE_PIN AG12 [get_ports {m1_ddr4_dm_n[3]}]
set_property PACKAGE_PIN AL18 [get_ports {m1_ddr4_dm_n[6]}]
set_property PACKAGE_PIN AG19 [get_ports {m1_ddr4_dm_n[7]}]
set_property PACKAGE_PIN AR10 [get_ports {m1_ddr4_dq[11]}]
set_property PACKAGE_PIN AR11 [get_ports {m1_ddr4_dq[13]}]
set_property PACKAGE_PIN AP9  [get_ports {m1_ddr4_dq[15]}]
set_property PACKAGE_PIN AJ12 [get_ports {m1_ddr4_dq[28]}]
set_property PACKAGE_PIN AH12 [get_ports {m1_ddr4_dq[29]}]
set_property PACKAGE_PIN AR18 [get_ports {m1_ddr4_dq[44]}]
set_property PACKAGE_PIN AK20 [get_ports {m1_ddr4_dq[55]}]
set_property PACKAGE_PIN AJ22 [get_ports {m1_ddr4_dq[56]}]
set_property PACKAGE_PIN AJ19 [get_ports {m1_ddr4_dq[60]}]
set_property PACKAGE_PIN AH19 [get_ports {m1_ddr4_dq[61]}]
set_property PACKAGE_PIN AF20 [get_ports {m1_ddr4_dq[62]}]
set_property PACKAGE_PIN AL21 [get_ports {m1_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN AK21 [get_ports {m1_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN AH20 [get_ports {m1_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN AG20 [get_ports {m1_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN AK15 [get_ports m1_ddr4_reset_n]
set_property PACKAGE_PIN AF21 [get_ports {m1_ddr4_dq[63]}]
set_property PACKAGE_PIN AH21 [get_ports {m1_ddr4_dq[59]}]
set_property PACKAGE_PIN AH22 [get_ports {m1_ddr4_dq[57]}]
set_property PACKAGE_PIN AJ21 [get_ports {m1_ddr4_dq[58]}]
set_property PACKAGE_PIN AK19 [get_ports {m1_ddr4_dq[54]}]
set_property PACKAGE_PIN AL20 [get_ports {m1_ddr4_dq[49]}]
set_property PACKAGE_PIN AL22 [get_ports {m1_ddr4_dq[53]}]
set_property PACKAGE_PIN AM19 [get_ports {m1_ddr4_dq[51]}]
set_property PACKAGE_PIN AN21 [get_ports {m1_ddr4_dq[47]}]
set_property PACKAGE_PIN AN20 [get_ports {m1_ddr4_dq[46]}]
set_property PACKAGE_PIN AP18 [get_ports {m1_ddr4_dq[40]}]
set_property PACKAGE_PIN AP19 [get_ports {m1_ddr4_dq[41]}]
set_property PACKAGE_PIN AP21 [get_ports {m1_ddr4_dm_n[5]}]
set_property PACKAGE_PIN AP22 [get_ports {m1_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN AR19 [get_ports {m1_ddr4_dq[45]}]
set_property PACKAGE_PIN AR20 [get_ports {m1_ddr4_dq[43]}]
set_property PACKAGE_PIN AT20 [get_ports {m1_ddr4_dq[42]}]
set_property PACKAGE_PIN AT22 [get_ports {m1_ddr4_dq[39]}]
set_property PACKAGE_PIN AU22 [get_ports {m1_ddr4_dq[38]}]
set_property PACKAGE_PIN AV19 [get_ports {m1_ddr4_dq[37]}]
set_property PACKAGE_PIN AV21 [get_ports {m1_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN AW19 [get_ports {m1_ddr4_dq[36]}]
set_property PACKAGE_PIN AW21 [get_ports {m1_ddr4_dq[32]}]
set_property PACKAGE_PIN AW22 [get_ports {m1_ddr4_dq[33]}]
set_property PACKAGE_PIN AL16 [get_ports {m1_ddr4_odt[0]}]
set_property PACKAGE_PIN AN16 [get_ports {m1_ddr4_bg[0]}]
set_property PACKAGE_PIN AN15 [get_ports {m1_ddr4_bg[1]}]
set_property PACKAGE_PIN AN17 [get_ports {m1_ddr4_adr[4]}]
set_property PACKAGE_PIN AP13 [get_ports {m1_ddr4_adr[6]}]
set_property PACKAGE_PIN AP14 [get_ports {m1_ddr4_adr[0]}]
set_property PACKAGE_PIN AP16 [get_ports {m1_ddr4_ba[0]}]
set_property PACKAGE_PIN AP17 [get_ports {m1_ddr4_adr[5]}]
set_property PACKAGE_PIN AR13 [get_ports {m1_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AR14 [get_ports {m1_ddr4_adr[1]}]
set_property PACKAGE_PIN AR15 [get_ports {m1_ddr4_adr[2]}]
set_property PACKAGE_PIN AR16 [get_ports {m1_ddr4_ba[1]}]
set_property PACKAGE_PIN AT15 [get_ports {m1_ddr4_adr[3]}]
set_property PACKAGE_PIN AT16 [get_ports {m1_ddr4_adr[10]}]
set_property PACKAGE_PIN AT17 [get_ports {m1_ddr4_adr[9]}]
set_property PACKAGE_PIN AU15 [get_ports {m1_ddr4_adr[11]}]
set_property PACKAGE_PIN AV14 [get_ports {m1_ddr4_adr[13]}]
set_property PACKAGE_PIN AV15 [get_ports {m1_ddr4_adr[12]}]
set_property PACKAGE_PIN AV16 [get_ports {m1_ddr4_adr[7]}]
set_property PACKAGE_PIN AW14 [get_ports {m1_ddr4_adr[14]}]
set_property PACKAGE_PIN AW16 [get_ports {m1_ddr4_adr[8]}]
set_property PACKAGE_PIN AW17 [get_ports {m1_ddr4_adr[16]}]
set_property PACKAGE_PIN AW18 [get_ports {m1_ddr4_adr[15]}]
set_property PACKAGE_PIN AG9  [get_ports {m1_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN AG10 [get_ports {m1_ddr4_dq[27]}]
set_property PACKAGE_PIN AH10 [get_ports {m1_ddr4_dq[26]}]
set_property PACKAGE_PIN AJ9  [get_ports {m1_ddr4_dq[31]}]
set_property PACKAGE_PIN AJ11 [get_ports {m1_ddr4_dq[25]}]
set_property PACKAGE_PIN AK9  [get_ports {m1_ddr4_dq[30]}]
set_property PACKAGE_PIN AK10 [get_ports {m1_ddr4_dq[24]}]
set_property PACKAGE_PIN AK11 [get_ports {m1_ddr4_dq[21]}]
set_property PACKAGE_PIN AL8  [get_ports {m1_ddr4_dq[23]}]
set_property PACKAGE_PIN AL10 [get_ports {m1_ddr4_dq[20]}]
set_property PACKAGE_PIN AL12 [get_ports {m1_ddr4_dm_n[2]}]
set_property PACKAGE_PIN AM7  [get_ports {m1_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AM8  [get_ports {m1_ddr4_dq[22]}]
set_property PACKAGE_PIN AM9  [get_ports {m1_ddr4_dq[16]}]
set_property PACKAGE_PIN AM10 [get_ports {m1_ddr4_dq[17]}]
set_property PACKAGE_PIN AN9  [get_ports {m1_ddr4_dq[18]}]
set_property PACKAGE_PIN AN10 [get_ports {m1_ddr4_dq[19]}]
set_property PACKAGE_PIN AN11 [get_ports {m1_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN AP8  [get_ports {m1_ddr4_dq[14]}]
set_property PACKAGE_PIN AP11 [get_ports {m1_ddr4_dq[8]}]
set_property PACKAGE_PIN AP12 [get_ports {m1_ddr4_dq[9]}]
set_property PACKAGE_PIN AR9  [get_ports {m1_ddr4_dm_n[1]}]
set_property PACKAGE_PIN AT10 [get_ports {m1_ddr4_dq[10]}]
set_property PACKAGE_PIN AT11 [get_ports {m1_ddr4_dq[12]}]
set_property PACKAGE_PIN AT12 [get_ports {m1_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AU9  [get_ports {m1_ddr4_dm_n[0]}]
set_property PACKAGE_PIN AU10 [get_ports {m1_ddr4_dq[7]}]
set_property PACKAGE_PIN AU13 [get_ports {m1_ddr4_dq[1]}]
set_property PACKAGE_PIN AV10 [get_ports {m1_ddr4_dq[6]}]
set_property PACKAGE_PIN AV11 [get_ports {m1_ddr4_dq[5]}]
set_property PACKAGE_PIN AV12 [get_ports {m1_ddr4_dq[0]}]
set_property PACKAGE_PIN AW11 [get_ports {m1_ddr4_dq[4]}]
set_property PACKAGE_PIN AW12 [get_ports {m1_ddr4_dq[2]}]
set_property PACKAGE_PIN AW13 [get_ports {m1_ddr4_dq[3]}]
set_property PACKAGE_PIN AU20 [get_ports {m1_ddr4_dm_n[4]}]
set_property PACKAGE_PIN AU18 [get_ports {m1_ddr4_dq[34]}]
set_property PACKAGE_PIN AU19 [get_ports {m1_ddr4_dq[35]}]
set_property PACKAGE_PIN AM20 [get_ports {m1_ddr4_dq[48]}]
set_property PACKAGE_PIN AM22 [get_ports {m1_ddr4_dq[52]}]
set_property PACKAGE_PIN AN19 [get_ports {m1_ddr4_dq[50]}]

#
# Bank B - ECC pins
#
#set_property PACKAGE_PIN AH17 [get_ports {m1_ddr4_dq[64]}]
#set_property PACKAGE_PIN AG17 [get_ports {m1_ddr4_dq[65]}]
#set_property PACKAGE_PIN AJ13 [get_ports {m1_ddr4_dq[66]}]
#set_property PACKAGE_PIN AJ14 [get_ports {m1_ddr4_dq[67]}]
#set_property PACKAGE_PIN AJ16 [get_ports {m1_ddr4_dq[68]}]
#set_property PACKAGE_PIN AJ17 [get_ports {m1_ddr4_dq[69]}]
#set_property PACKAGE_PIN AG15 [get_ports {m1_ddr4_dq[70]}]
#set_property PACKAGE_PIN AF15 [get_ports {m1_ddr4_dq[71]}]
#set_property PACKAGE_PIN AG14 [get_ports {m1_ddr4_dm_n[8]}]
#set_property PACKAGE_PIN AH15 [get_ports {m1_ddr4_dqs_c[8]}]
#set_property PACKAGE_PIN AH16 [get_ports {m1_ddr4_dqs_t[8]}]